##############################
#### INTERFACE PARAMETERS ####
##############################
interface:
  theme: theme-dark
  transition:
    page: 500
  languages:
    available:
      - fr
      - en
    current: en
  map:
    levels: [ -5.13280186540815, 41.36591212487376, 9.559580918100119, 51.08754085980848 ]
    animation:
      minspeed: 300
      maxspeed: 1500
    start:
      centers:
        - [-0.5810662583798712, 44.846338628363654]
        - [1.4372954714383932, 43.60142145652701]
        - [5.377944111438339, 43.29630636416908]
        - [7.260848879564221, 43.70687562259085]
        - [4.856364291172863, 45.75191397557511]
        - [3.083754673631176, 45.77745081502012]
        - [1.2595188767111398, 45.83144384871421]
        - [-1.5513545630630488, 47.218249561100286]
        - [-1.6663928183473948, 48.10743597257625]
        - [-4.48543194405423, 48.392941224531135]
        - [2.3451688301809464, 48.856940737728145]
        - [-1.6216207845868778, 49.63773675305673]
        - [0.12058984374020455, 49.49742277536755]
        - [3.0572813222081736, 50.64223173666884]
        - [2.288637849351305, 49.901992863566164]
        - [7.750242063199694, 48.57490450755704]
        - [6.1920243713659735, 48.68980641544863]
        - [4.035097508972273, 49.2595447181902]
        - [1.9062699486658305, 47.902773351516984]
      zoom: 6
#########################
#### GAME PARAMETERS ####
#########################
game:
  colors:
    - white
    - sand
    - brown
    - grey
  score:
    increment:
      default: 1
      movement: 1
    refresh:
      default: 1000
      movement: 200
    modifier:
      enemies: 50
      position: 5
      helpers: -20
  tolerance:
    flag: 500
    target: 300
    enemies:
      hunter: 1500
      eagle: 1000
      snake: 500
    helpers: 200
  visibility:
    helpers: 2500
  speed:
    travel: 4000 # in km/h
    roaming: 20 # in px/s
    enemies: 10 # in px/s
  invulnerability: 3000
  routing: 12.5
  wrong:
    - Aïe, non, pas là !
    - Non non, pas ici !
    - Ouch, Tu veux ma mort ?!
    - Prends ton temps avant de cliquer n'importe où !
    - Eh, tu veux que je te morde ?!
  lost:
    - Hé ho ! Tu t'égares...
    - Non, c'est pas par là !
    - Mais écoute-moi, tu vas te perdres !
    - Mes indications sont pas assez claires ?
    - Où tu vas comme ça ?
###########################
#### FORM DEFINITION ######
###########################
form:
  - question: 'Genre<br>(Sélectionnez les réponses applicables)'
    mandatory: false
    multiple: true
    answers:
      - text: Femme
        unique: false
      - text: Homme
        unique: false
      - text: Trans
        unique: false
      - text: Ne se prononce pas
        unique: true
  - question: 'Catégorie d''âge'
    mandatory: false
    multiple: false
    answers:
      - text: 18-24
        unique: true
      - text: 25-34
        unique: true
      - text: 35-44
        unique: true
      - text: 45-59
        unique: true
      - text: 60 et plus
        unique: true
      - text: Ne se prononce pas
        unique: true
  - question: 'Vous utilisez une carte interactive<br>(Google Maps, Apple Maps, OpenStreetMap, etc.)'
    mandatory: false
    multiple: false
    answers:
      - text: Tous les jours
        unique: true
      - text: Plusieurs fois par semaine
        unique: true
      - text: Plusieurs fois par mois
        unique: true
      - text: Presque jamais
        unique: true
      - text: Ne se prononce pas
        unique: true
consent:
  - type: paragraph
    content: 'J''accepte que mes données de jeux
      soient collectées et utilisées par l''équipe LostInZoom
      afin de mieux comprendre comment nous naviguons dans
      les cartes interactives.'
  - type: list
    title: 'Les données suivantes sont collectées:'
    content:
      - 'Les réponses aux formulaires sociologiques et cognitifs.'
      - 'Le métriques de jeux, à savoir le temps passé, le score et la distance parcourue par niveau.'
      - 'Les interactions avec la carte pendant un niveau, à savoir les déplacements latéraux,
        les zooms en avant et en arrière.'
      - 'Les informations sur votre appareil, à savoir le type (téléphone mobile ou tablette),
        le système d''exploitation (Android, iOS, etc.) et taille de l''écran.'
  - type: paragraph
    content: 'Nous ne collectons aucune information personnelle tel que votre nom, votre
      localisation ou votre adresse IP.'
  - type: paragraph
    content: 'Les données collectées ne seront jamais dévoilées au-delà de notre équipe
      de recherche. Ceci étant dit, nous les utiliserons pour conduire des analyses
      statistiques, et les résultats de ces analyses pourront être sujets à une ou
      plusieurs publications scientifiques.'
  - type: paragraph
    content: 'En signant ce formulaire et en continuant le jeu, vous comprenez et acceptez
      de partager ces données avec notre équipe.'
###########################
#### LEVELS DEFINITION ####
###########################
levels:
  - type: tutorial
    name: "Tutoriel"
    player: [3.5607160720497193,45.504232060218484]
    target: [3.741964538569108,45.55022042474076]
    hints:
      0: À l'ouest de la ville de Lyon
      6: Entre St-Étienne et Clermont-Ferrand
      8: Au sud-ouest de la ville d'Ambert
      10: Entre St-Amant-Roche-Savine et St-Germain-l'Herm
      11: Au sud-ouest de Fournols
      13: Au hameau de La Colombière, double-cliquez sur votre position
    enemies:
      - [3.5891028350278966,45.491286197997574]
      - [3.588019736289834,45.515975273288184]
      - [3.6127788326561507,45.497240656813894]
      - [3.6318083843088247,45.49725362798065]
      - [3.663120421178209,45.51831989564912]
      - [3.694075467553683,45.51860817504424]
      - [3.7282743304201134,45.54380236684891]
      - [3.6190975823646476,45.542915891045745]
      - [3.636248217769057,45.56781305524764]
      - [3.644740890465124,45.53639115011499]
      - [3.6992120343482786,45.546318900483904]
      - [3.6764900475517597,45.553593565608566]
    helpers:
      - [3.576301842229193,45.519260260104765]
      - [3.600610253817467,45.48481341036346]
      - [3.613377110635374,45.53048865898132]
      - [3.651153064963168,45.50359554095096]
      - [3.682939951291738,45.51360147101689]
      - [3.654087860996387,45.551191847563416]
      - [3.7180748586842203,45.52810168682577]
      - [3.7297718219987406,45.55675942421688]
      - [3.7423176932567546,45.51605641047329]
  - type: experience
    name: "Niveau 1"
    index: "piaget"
    title: 'Expérience 1 :<br>Les bouteilles'
    presentation:
      - 'Vous devez dessiner le niveau d''eau dans différentes bouteilles.'
    top: 'Voici une bouteille, la ligne bleue indique le niveau d''eau.'
    bottom: 'Dessinez le même niveau dans cette bouteille pivotée.'
  - type: tier
    name: "Niveau 2"
    content:
      - player: [ -3.1053235400638313,48.27263956517598 ]
        target: [ -2.9660401282860756,48.06515374496134 ]
        hints:
          0: Je pense que je suis à l'ouest de la ville de Rennes.
          6: Je crois être entre Lorient et St-Brieuc.
          8: Hmm... au nord de Pontivy ?
          10: Ça me revient, je suis entre Gouarec et Corlay.
          11: Ah oui, c'est ça ! À St-Igeaux !
        enemies:
          - type: snake
            coordinates: [-3.180709285767183,48.22721521917229]
          - type: eagle
            coordinates: [-2.986731929810153,48.200448665578335]
          - type: eagle
            coordinates: [-3.0938057136846635,48.219495533891376]
          - type: hunter
            coordinates: [-3.015951492495701,48.17039484156545]
          - type: snake
            coordinates: [-3.1532805940582023,48.13466339677635]
          - type: hunter
            coordinates: [-3.070711471743748,48.123893276292826]
          - type: snake
            coordinates: [-2.9855245134307613,48.12999471231148]
          - type: hunter
            coordinates: [-3.00568882759332,48.25581780903966]
          - type: eagle
            coordinates: [-3.0681395126455033,48.17696967143539]
        helpers:
          - [-3.1268076134038996,48.19953332236447]
          - [-3.147403814937377,48.21490323562907]
          - [-3.1276953423665743,48.16411991213865]
          - [-3.0504211956319827,48.23552701580077]
          - [-3.0232128673849084,48.0725072092649]
          - [-3.084452800933297,48.19445732193535]
          - [-2.9924719141086507,48.08597533301749]
          - [-2.932125467956304,48.139081456362646]
          - [-3.2087120655625054,48.20443641871421]
          - [-3.01009985242774,48.20964171694654]
      - target: [ 1.9150105563803137,48.02224855414998 ]
      - target: [ 4.742646559356173,45.9924037536202 ]
      - target: [ -0.38898848432943517,45.10183756639063 ]
  - type: experience
    name: "Niveau 3"
    index: "sbsod"
    title: 'Expérience 2 :<br>Les cartes et vous'
    presentation:
      - 'Cette expérience est un simple questionnaire dans lequel vous
        devez répondre à quinze questions sur vos habitudes et votre aisance à
        manipuler des cartes.'
      - 'Merci de répondre le plus honnêtement possible,
        sur une échelle de 1 (pas du tout d''accord) à 7 (tout à fait d''accord).'
    content:
      - "Je suis très doué·e pour indiquer une direction."
      - "J’ai généralement une mauvaise mémoire de l’endroit où je laisse un objet."
      - "Je suis très doué·e pour évaluer les distances."
      - "J’ai un très bon sens de l’orientation."
      - "J’ai tendance à penser à mon environnement en termes de directions Nord, Sud, Est, Ouest."
      - "Je me perds très facilement dans une nouvelle ville."
      - "J’aime lire des cartes."
      - "J’ai des difficultés à comprendre les indications directionnelles."
      - "Je suis très doué·e pour lire les cartes."
      - "Je ne mémorise pas très bien la route lorsque je voyage en voiture en tant que passager·ère."
      - "Je n’aime pas indiquer une direction."
      - "Ce n’est pas important pour moi de savoir où je suis."
      - "Je laisse généralement quelqu’un d’autre planifier l’itinéraire pour les longs voyages."
      - "Je peux généralement me rappeler un nouveau trajet après ne l’avoir suivi qu’une fois."
      - "Je n’ai pas une très bonne carte mentale de mon environnement."
  - type: tier
    name: "Niveau 4"
    content:
      - target: [ 1.2866479982915493,43.885279168322626 ]
      - target: [ 6.089149305028605,45.91959117838756 ]
      - target: [ 1.361450712000182,45.950810067261486 ]
      - player: [ -1.5217619972838459,49.42123384435775 ]
        target: [ -1.6178715125171268,49.64454227099347 ]
        hints:
          0: Au Nord de Rennes
          7: Au sud de Cherbourg
          9: Entre Cherbourg-en-Cotentin et Lessay
          10: Au nord de St-Sauveur le Vicomte
          11: Dans le village de Ste-Colombe
        enemies:
          - [-1.5962995724863411,49.59770396257331]
          - [-1.6492258301283464,49.620577848469765]
          - [-1.5757475056945813,49.635431513095874]
          - [-1.6315608864769122,49.63571511787971]
          - [-1.5739959417489602,49.5635417171812]
          - [-1.66735428166063,49.55933395164491]
          - [-1.6244827781362379,49.59134044315358]
          - [-1.5943034960499878,49.52291249068318]
          - [-1.6763074354000054,49.53775238950017]
          - [-1.6838284190400439,49.51855423006732]
          - [-1.6313740564569823,49.52082060690705]
          - [-1.6413872138595051,49.47004255729322]
          - [-1.626021587249309,49.4741104670295]
          - [-1.5827786672248083,49.42688362085631]
          - [-1.4935011239182197,49.45562085360561]
          - [-1.549575413800516,49.49205765433281]
          - [-1.488285184814413,49.50225097647408]
          - [-1.4689505671391738,49.509226174861695]
          - [-1.4979524936520328,49.51898978198184]
        helpers:
          - [-1.5424889143215943,49.419975913700256]
          - [-1.5426772096997319,49.458911616652934]
          - [-1.5608133626965695,49.46797241725518]
          - [-1.567591996309525,49.43884015645001]
          - [-1.5057406711645385,49.44448913727061]
          - [-1.5960846821852956,49.4822827242462]
          - [-1.5042332765884678,49.478028291666256]
          - [-1.5574606417868533,49.51862377143022]
          - [-1.6038514646661803,49.51101468400574]
          - [-1.651278127290819,49.50181879059534]
          - [-1.6395583404581469,49.442797132935105]
          - [-1.6654395363802976,49.518306749755226]
          - [-1.6170954156955257,49.55189961120284]
          - [-1.6478598561312898,49.5653393402111]
          - [-1.6620212652207684,49.6061788298084]
          - [-1.5658213483025853,49.589087389562515]
          - [-1.6195370379523322,49.61219106014636]
          - [-1.599027410995156,49.6137731027806]
          - [-1.6168512534698447,49.63338616536307]
          - [-1.6423392955582643,49.646578527429426]
          - [-1.6063771152243906,49.63881753504038]
  - type: experience
    name: "Niveau 5"
    index: "ptsot"
    timelimit: 30
    title: 'Expérience 3 :<br>Angles et orientation'
    presentation:
      - 'Vous incarnez un personnage, vous faites face à un
        second personnage et vous devrez estimez sur un cercle la position d''un troisième.'
    top:
      - type: characters
        subtype: images
    tutorial:
      - content:
        - text: Voici les personnages. Prenez le temps d'apprendre leur nom. Leur disposition ne changera pas.
        - type: characters
          subtype: names
      - content:
        - text: 'Voici un exemple pour commencer.<br>Vous êtes sur le pigeon et vous faites face au chat.
            Cliquez sur le cercle pour placer le lapin.'
        - type: tutorial
          character1: pigeon
          character2: cat
          character3: rabbit
      - content:
        - text: 'Vous avez compris ? Alors essayez !'
        - text: 'Vous êtes sur le lapin et vous faites face au chat.
            Cliquez sur le cercle pour placer le serpent.'
        - type: test
          character1: rabbit
          character2: cat
          character3: snake
      - content:
        - text: 'C''est parti ! Attention, cette fois vous avez 30 secondes par test.'
    tests:
      - content:
        - text: 'Imaginez que vous êtes sur l''<b>aigle</b> et que
            vous faites face au <b>chat</b>. Pointez le <b>pigeon</b> sur le cercle.'
        - type: test
          character1: eagle
          character2: cat
          character3: pigeon
        - type: timer
      - content:
        - text: 'Imaginez que vous êtes sur le <b>lapin</b> et que
            vous faites face au <b>pigeon</b>. Montrez l''<b>aigle</b> sur le cercle.'
        - type: test
          character1: rabbit
          character2: pigeon
          character3: eagle
        - type: timer
      - content:
        - text: 'Imaginez que vous êtes sur le <b>chasseur</b> et que
            vous faites face au <b>lapin</b>. Montrez le <b>serpent</b> sur le cercle.'
        - type: test
          character1: hunter
          character2: rabbit
          character3: snake
        - type: timer
      - content:
        - text: 'Imaginez que vous êtes sur le <b>lapin</b> et que
            vous faites face à la <b>courgette</b>. Montrez l''<b>aigle</b> sur le cercle.'
        - type: test
          character1: rabbit
          character2: zucchini
          character3: eagle
        - type: timer
      - content:
        - text: 'Imaginez que vous êtes sur le <b>chasseur</b> et que
            vous faites face au <b>pigeon</b>. Montrez le <b>chat</b> sur le cercle.'
        - type: test
          character1: hunter
          character2: pigeon
          character3: cat
        - type: timer
      - content:
        - text: 'Imaginez que vous êtes sur le <b>lapin</b> et que
            vous faites face au <b>chat</b>. Montrez le <b>serpent</b> sur le cercle.'
        - type: test
          character1: rabbit
          character2: cat
          character3: snake
        - type: timer
    characters:
      cat:
        name: 'Chat'
        coordinates: [13.55, 27.41]
      eagle:
        name: 'Aigle'
        coordinates: [43.86, 15.23]
      hunter:
        name: 'Chasseur'
        coordinates: [68.19, 27.18]
      snake:
        name: 'Serpent'
        coordinates: [87.74, 47.27]
      rabbit:
        name: 'Lapin'
        coordinates: [52, 50.65]
      pigeon:
        name: 'Pigeon'
        coordinates: [23.31, 78.9]
      zucchini:
        name: 'Courgette'
        coordinates: [67.42, 84.01]
  - type: tier
    name: "Niveau 6"
    content:
      - target: [1.2866479982915493,43.885279168322626]
      - target: [6.089149305028605,45.91959117838756]
      - target: [1.361450712000182,45.950810067261486]
      - target: [-1.5260220720508781,49.5499857870286]
  - type: experience
    name: "Niveau 7"
    index: "purdue"
    timelimit: 30
    title: 'Expérience 4 :<br>Rotation en 3D'
    presentation:
      - 'Retrouver un objet en trois dimensions ayant subi une rotation.'
    tutorial:
      text1: 'Voici la rotation d''un solide en trois dimensions :'
      text2: 'Voici un autre solide :'
      text3: 'Appliquez la même rotation et trouvez le bon résultat pour continuer :'
      solution: 3
    tests:
      - 2
      - 3
      - 1
      - 1
      - 0
      - 3
  - type: tier
    name: "Niveau 8"
    content:
      - target: [1.2866479982915493,43.885279168322626]
      - target: [6.089149305028605,45.91959117838756]
      - target: [1.361450712000182,45.950810067261486]
      - target: [-1.5260220720508781,49.5499857870286]