#########################
#### GAME PARAMETERS ####
#########################
game:
  version: '1.0'
  codename: livia
  name: Mapinou
  description: Naviguez dans des cartes et trouvez des lapins.
  colors:
    - white
    - sand
    - brown
    - grey
  score:
    increment:
      default: 1
      movement: 1
    refresh:
      default: 1000
      movement: 200
    modifier:
      enemies: 50
      position: 5
      helpers: -20
  tolerance:
    target: 300
    enemies:
      hunter: 1500
      eagle: 1000
      snake: 500
    helpers: 200
  visibility:
    helpers: 2500
  speed:
    travel: 4000 # in km/h
    roaming: 20 # in px/s
  invulnerability: 3000
  routing: 12.5
  wrong:
    - Aïe aïe aïe, pas par là !
    - Et non, c'est pas ici !
    - Pas par là.
    - Je ne suis pas ici.
  lost:
    - Reviens en arrière, Tu t'égares...
    - Ce n'est pas par là, reviens en arrière !
    - Ce n'est pas la bonne direction, reviens où tu étais.
    - Tu refroidis, retourne en arrière !
##############################
#### INTERFACE PARAMETERS ####
##############################
interface:
  transition:
    page: 500
  map:
    levels: [ -7, 42, 12, 52 ]
    animation:
      minspeed: 500
      maxspeed: 1500
    start:
      centers:
        - [-0.5810662583798712, 44.846338628363654]
        - [1.4372954714383932, 43.60142145652701]
        - [5.377944111438339, 43.29630636416908]
        - [7.260848879564221, 43.70687562259085]
        - [4.856364291172863, 45.75191397557511]
        - [3.083754673631176, 45.77745081502012]
        - [1.2595188767111398, 45.83144384871421]
        - [-1.5513545630630488, 47.218249561100286]
        - [-1.6663928183473948, 48.10743597257625]
        - [-4.48543194405423, 48.392941224531135]
        - [2.3451688301809464, 48.856940737728145]
        - [-1.6216207845868778, 49.63773675305673]
        - [0.12058984374020455, 49.49742277536755]
        - [3.0572813222081736, 50.64223173666884]
        - [2.288637849351305, 49.901992863566164]
        - [7.750242063199694, 48.57490450755704]
        - [6.1920243713659735, 48.68980641544863]
        - [4.035097508972273, 49.2595447181902]
        - [1.9062699486658305, 47.902773351516984]
      zoom: 6
###########################
#### FORM DEFINITION ######
###########################
form:
  - question: 'Genre<br>(Choix multiple possible)'
    mandatory: false
    multiple: true
    answers:
      - text: Femme
        unique: false
      - text: Homme
        unique: false
      - text: Trans
        unique: false
      - text: Non-binaire
        unique: false
      - text: Ne se prononce pas
        unique: true
  - question: 'Catégorie d''âge'
    mandatory: false
    multiple: false
    answers:
      - text: 18-24
        unique: true
      - text: 25-34
        unique: true
      - text: 35-44
        unique: true
      - text: 45-59
        unique: true
      - text: 60 et plus
        unique: true
      - text: Ne se prononce pas
        unique: true
  - question: 'Vous utilisez une carte interactive<br>(Google Maps, Apple Maps, OpenStreetMap, etc.)'
    mandatory: false
    multiple: false
    answers:
      - text: Tous les jours
        unique: true
      - text: Plusieurs fois par semaine
        unique: true
      - text: Plusieurs fois par mois
        unique: true
      - text: Presque jamais
        unique: true
      - text: Ne se prononce pas
        unique: true
consent:
  - type: paragraph
    content: 'J''accepte que mes données de jeux
      soient collectées et utilisées par l''équipe LostInZoom
      afin de mieux comprendre comment nous naviguons dans
      les cartes interactives.'
  - type: list
    title: 'Les données suivantes sont collectées:'
    content:
      - 'Les réponses aux formulaires sociologiques et cognitifs.'
      - 'Les métriques de jeux, à savoir le temps passé, le score et la distance parcourue par niveau.'
      - 'Les interactions avec la carte pendant un niveau, à savoir les déplacements latéraux,
        les zooms en avant et en arrière.'
      - 'Les informations sur votre appareil, à savoir le type (téléphone mobile ou tablette),
        le système d''exploitation (Android, iOS, etc.) et taille de l''écran.'
  - type: paragraph
    content: 'Nous ne collectons aucune information personnelle tel que votre nom, votre
      localisation ou votre adresse IP.'
  - type: paragraph
    content: 'Les données collectées seront utilisées pour conduire des analyses
      statistiques, et les résultats de ces analyses pourront être sujets à une ou
      plusieurs publications scientifiques. Ces données seront donc disponibles librement
      en ligne.'
  - type: paragraph
    content: 'En signant ce formulaire et en continuant le jeu, vous comprenez et acceptez
      de partager ces données avec notre équipe.'